### ISSUE TITLE
Finalize a control layout and have graphics made

### ISSUE THREAD

**Issue by T99** [frc1711/Euphrosyne#24]
Let's nail down a final layout for both controllers with Miles and Andrew that everyone is comfortable with. Let's also make some simple graphics labelling all of the buttons that we can print a bunch of and have them everywhere.

I know there was conversation at some point regarding have intaking and/or shooting on the driver 1 controller?

**Comment by Dr-WaSaBi** [comment]
Do we know the model number of the new controllers?  I can get started on this and mock up the control mapping images..

**Comment by Dr-WaSaBi** [comment]
answered my own question.
PowerA Enhanced Wired Controller for Xbox
