### ISSUE TITLE
Driver / Operator limits meet with haptic feed back using HIDRumble

### ISSUE THREAD

**Issue by Dr-WaSaBi** [frc1711/Euphrosyne#26]
Could we provide the driver and or the operator haptic feed back that they have reached a limit, or are close to a limit using the HIDRumble functions in the WPILIB?

```java
// Copyright (c) FIRST and other WPILib contributors.
// Open Source Software; you can modify and/or share it under the terms of
// the WPILib BSD license file in the root directory of this project.

package edu.wpi.first.wpilibj.examples.hidrumble;

import edu.wpi.first.wpilibj.GenericHID.RumbleType;
import edu.wpi.first.wpilibj.TimedRobot;
import edu.wpi.first.wpilibj.XboxController;

/** This is a demo program showing the use of GenericHID's rumble feature. */
public class Robot extends TimedRobot {
  private final XboxController m_hid = new XboxController(0);

  @Override
  public void autonomousInit() {
    // Turn on rumble at the start of auto
    m_hid.setRumble(RumbleType.kLeftRumble, 1.0);
    m_hid.setRumble(RumbleType.kRightRumble, 1.0);
  }

  @Override
  public void disabledInit() {
    // Stop the rumble when entering disabled
    m_hid.setRumble(RumbleType.kLeftRumble, 0.0);
    m_hid.setRumble(RumbleType.kRightRumble, 0.0);
  }
}
```

**Comment by Dr-WaSaBi** [comment]
### Possible uses for haptic feedback.

- When the climber is already extended, and the operator accidentally tries to extend them more, rumble his/her controller. Also maybe flash something on the driver station.
🛑*This could be useful for any button pressed by mistake* 
- If the vision system says the robot is passing through the range we can shoot a high goal (week 6 dreaming here) it would rumble the controller to let the driver know we are in range.  
- If the driver stops the robot in range of the goal, rumble the operators controller letting them know they are in range.

What else folks? 🤔

**Comment by T99** [comment]
@Dr-WaSaBi I love it!!
